services:
  composer:
    image: composer
    volumes:
      - ./:/app
    working_dir: /app
  php:
    build:
      context: Docker/PHP
    environment:
      - XDEBUG_MODE=coverage
    volumes:
      - ./:/app
    working_dir: /app
